# Generated by Django 3.2.2 on 2021-05-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ec2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst_name', models.CharField(max_length=70)),
                ('key_name', models.CharField(max_length=70)),
                ('ami_id', models.CharField(max_length=70)),
                ('inst_type', models.CharField(max_length=70)),
            ],
        ),
    ]
