# Generated by Django 3.2.2 on 2021-05-19 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210518_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='iam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('groupname', models.CharField(max_length=100)),
            ],
        ),
    ]
