# Generated by Django 3.2.2 on 2021-05-19 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_iam_usr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='iam_gname',
        ),
        migrations.RemoveField(
            model_name='project',
            name='iam_uname',
        ),
        migrations.RemoveField(
            model_name='project',
            name='instance',
        ),
    ]
