# Generated by Django 3.2.2 on 2021-05-19 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210519_0851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iam',
            old_name='usr',
            new_name='user',
        ),
    ]
