# Generated by Django 3.2.2 on 2021-05-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_usr_iam_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rds',
            name='rds_type',
            field=models.CharField(choices=[('RDS MySql', 'RDS MYSQL'), ('RDS PostGreSQl', 'RDS PostgreSQL'), ('AURORA MYSQL', 'Aurora Mysql')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='iam',
            name='groupname',
            field=models.CharField(choices=[('billing', 'Billing'), ('admin', 'Admin'), ('readonly', 'ReadOnly')], max_length=100),
        ),
    ]
