# Generated by Django 3.2.2 on 2021-05-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210519_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='email',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
