# Generated by Django 3.2.2 on 2021-05-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_project_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='budget',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
