# Generated by Django 3.2.2 on 2021-05-24 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_project_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='env_name',
            new_name='Environment_Name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='p_name',
            new_name='Project_Name',
        ),
    ]
