# Generated by Django 3.2.2 on 2021-05-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='final',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('env_name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('vpc_cidr', models.CharField(max_length=100)),
                ('rds_uname', models.CharField(max_length=100)),
                ('rds_password', models.CharField(max_length=100)),
                ('rds_type', models.CharField(max_length=100)),
                ('iam_umane', models.CharField(max_length=100)),
                ('iam_gname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('budget', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
