# Generated by Django 3.2.2 on 2021-05-26 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_final'),
    ]

    operations = [
        migrations.RenameField(
            model_name='final',
            old_name='budget',
            new_name='Budget',
        ),
        migrations.RenameField(
            model_name='final',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='final',
            old_name='env_name',
            new_name='Environment_Name',
        ),
        migrations.RenameField(
            model_name='final',
            old_name='iam_gname',
            new_name='IAM_Password',
        ),
        migrations.RenameField(
            model_name='final',
            old_name='iam_umane',
            new_name='IAM_Username',
        ),
        migrations.RenameField(
            model_name='final',
            old_name='p_name',
            new_name='Project_Name',
        ),
        migrations.RenameField(
            model_name='final',
            old_name='rds_password',
            new_name='RDS_Password',
        ),
        migrations.RenameField(
            model_name='final',
            old_name='rds_type',
            new_name='RDS_Type',
        ),
        migrations.RenameField(
            model_name='final',
            old_name='rds_uname',
            new_name='RDS_Username',
        ),
        migrations.RenameField(
            model_name='final',
            old_name='region',
            new_name='Region',
        ),
        migrations.RenameField(
            model_name='final',
            old_name='vpc_cidr',
            new_name='VPC_CIDR',
        ),
    ]
