# Generated by Django 3.2.2 on 2021-05-26 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210526_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='final',
            old_name='IAM_Password',
            new_name='IAM_Groupname',
        ),
    ]
